apiVersion: v1
kind: Service
metadata:
  name: simplified-ninja-service
spec:
  selector:
    app: simplified-ninja
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
